name: alice
description: Alice is an HTTP Inspector tool which helps debugging http requests. It catches and stores http requests and responses, which can be viewed via simple UI.
version: 0.3.4
#author: Jakub Homlala <jhomlala@gmail.com>
homepage: https://github.com/jhomlala/alice

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.2
  dio: ^5.4.0
  flutter_local_notifications: ^16.3.0
  rxdart: ^0.27.7

  path_provider: ^2.1.2
  permission_handler: ^11.0.1
  package_info_plus: ^5.0.1
  open_file: ^3.3.2
  sensors: ^2.0.3
  share: ^2.0.4
  chopper: ^7.0.10 
  collection: ^1.17.1

dev_dependencies:
  lint: ^2.1.2
