name: alice
description: Alice is an HTTP Inspector tool which helps debugging http requests. It catches and stores http requests and responses, which can be viewed via simple UI.
version: 0.2.5
#author: Jakub Homlala <jhomlala@gmail.com>
homepage: https://github.com/jhomlala/alice

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.10.3"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  dio: ^4.0.6
  flutter_local_notifications: ^12.0.4
  rxdart: ^0.27.7

  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  package_info_plus: ^3.0.2
  sensors: ^2.0.3
  share: ^2.0.4
  chopper: ^4.0.1
  better_player: ^0.0.83
  collection: ^1.16.0

dev_dependencies:
  lint: ^2.0.1
